### ISSUE TITLE
Untrusted Proxy / Why is there a proxy at all?

### ISSUE THREAD

**Issue by mnemocron** [Forichok/TelegramOnlineSpy#2]
Why is there a proxy on [line 15](https://github.com/Forichok/TelegramOnlineSpy/blob/master/spy.py#L15) required?

My network settings don't trust this domain (digitalresistance.dog).
It looks very sketchy to me that there is also an undocumented "secret".

**Comment by Forichok** [comment]
That proxy doesn't work anymore. I use it just because telegram is blocked
in Russia. If telegram is free to use in your country,  you can skip that

**Comment by mnemocron** [comment]
Thanks for the reply. And sorry for my tinfoil hat.
My server was misbehaving lately. So I looked into the newly installed stuff I had there.
You can close the issue imo.

**Comment by mnemocron** [comment]
I finally edited the code to make it work for me.
You can see the changes in my fork: [mnemocron/TelegramOnlineSpy](https://github.com/mnemocron/TelegramOnlineSpy)

Perhaps you might want to copy parts of my readme for better documentation.

**Comment by Forichok** [comment]
Thanks for editing my code and beautify the docs. Btw can you make a pull
request, so I can add your changes to my repo, please?
